### ISSUE TITLE
Transparency failed when enable depth test on polylines.

### ISSUE THREAD

**Issue by akira-cn** [oframe/ogl#55] opened 2020-03-02 09:23 UTC
The transparent options take no effect sometimes when I use polyline.

```js
import {Renderer, Camera, Transform, Program, Mesh, Plane, Polyline, Orbit, Vec3, Color} from '../src/index.mjs';

const vertex = /* glsl */ `
  precision highp float;
  precision highp int;

  attribute vec3 position;
  attribute vec3 normal;

  uniform mat3 normalMatrix;
  uniform mat4 modelViewMatrix;
  uniform mat4 projectionMatrix;

  void main() {
      gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
  }
`;

const fragment = /* glsl */ `
  precision highp float;
  precision highp int;

  uniform vec3 uColor;

  void main() {
      gl_FragColor.rgb = uColor;
      gl_FragColor.a = 0.2;
  }
`;


  const polylineVertex = /* glsl */ `
    precision highp float;
    attribute vec3 position;
    attribute vec3 next;
    attribute vec3 prev;
    attribute vec2 uv;
    attribute float side;
    uniform mat4 modelViewMatrix;
    uniform mat4 projectionMatrix;
    uniform vec2 uResolution;
    uniform float uDPR;
    uniform float uThickness;
    uniform float uMiter;
    varying vec2 vUv;
    vec4 getPosition() {
        mat4 mvp = projectionMatrix * modelViewMatrix;
        vec4 current = mvp * vec4(position, 1);
        vec4 nextPos = mvp * vec4(next, 1);
        vec4 prevPos = mvp * vec4(prev, 1);
        vec2 aspect = vec2(uResolution.x / uResolution.y, 1);    
        vec2 currentScreen = current.xy / current.w * aspect;
        vec2 nextScreen = nextPos.xy / nextPos.w * aspect;
        vec2 prevScreen = prevPos.xy / prevPos.w * aspect;
    
        vec2 dir1 = normalize(currentScreen - prevScreen);
        vec2 dir2 = normalize(nextScreen - currentScreen);
        vec2 dir = normalize(dir1 + dir2);
    
        vec2 normal = vec2(-dir.y, dir.x);
        normal /= mix(1.0, max(0.3, dot(normal, vec2(-dir1.y, dir1.x))), uMiter);
        normal /= aspect;
        float pixelWidthRatio = 1.0 / (uResolution.y / uDPR);
        float pixelWidth = current.w * pixelWidthRatio;
        normal *= pixelWidth * uThickness;
        current.xy -= normal * side;

        return current;
    }
    void main() {
        vUv = uv;
        gl_Position = getPosition();
    }
`;

const polylineFragment = /* glsl */ `
    precision highp float;
    uniform vec3 uColor;
    
    varying vec2 vUv;
    void main() {
        gl_FragColor.rgb = uColor;
        gl_FragColor.a = 0.2;
    }
`;

const renderer = new Renderer({dpr: 2, alpha: true, premultipliedAlpha: true});
const gl = renderer.gl;
document.body.appendChild(gl.canvas);
// gl.clearColor(1, 1, 1, 1);

const camera = new Camera(gl, {fov: 35});
camera.position.set(0, 0, 5);

// Create controls and pass parameters
const controls = new Orbit(camera, {
    target: new Vec3(0, 0, 0),
});

function resize() {
    renderer.setSize(window.innerWidth, window.innerHeight);
    camera.perspective({aspect: gl.canvas.width / gl.canvas.height});
}
window.addEventListener('resize', resize, false);
resize();

const scene = new Transform();

const geometry = new Plane(gl);

const program = new Program(gl, {
    transparent: true,
    vertex,
    fragment,
    uniforms: {
      uColor: {value: new Color('#f00')},
    },
    // Don't cull faces so that plane is double sided - default is gl.BACK
    cullFace: null,
});

const p1 = new Mesh(gl, {geometry, program});
p1.setParent(scene);
p1.position.z = 0.1;

const polyline = new Polyline(gl, {
  // points: [
  //   new Vec3(0, 0.5, -0.1),
  //   new Vec3(0, -1.0, -0.1),
  // ],
  points: [
    new Vec3(0, 0.5, 0.5),
    new Vec3(0, -1.0, 0.5),
  ],
  uniforms: {
    uColor: {value: new Color('#00f')},
    uThickness: {value: 12},
  }
});


// polyline.program.transparent = true;
// polyline.mesh.setParent(scene);
const polylineProgram = new Program(gl, {
  // depthTest: false,
  transparent: true,
  vertex: polylineVertex,
  fragment: polylineFragment,
  uniforms: {
    uResolution: {value: polyline.program.uniforms.uResolution.value},
    uDPR: {value: polyline.program.uniforms.uDPR.value},
    uMiter: {value: polyline.program.uniforms.uMiter.value},
    uColor: {value: new Color('#00f')},
    uThickness: {value: 12},
  }
});

const mesh = new Mesh(gl, {geometry: polyline.mesh.geometry, program: polylineProgram});
mesh.setParent(scene);

requestAnimationFrame(update);
function update() {
    requestAnimationFrame(update);
    controls.update();
    renderer.render({scene, camera});
}
```

The output graph seems no transparency.

![](https://p4.ssl.qhimg.com/t01c4f8bf6a3bf518aa.jpg)

But if I change `p1.position.z = 0.1;` to `p1.position.z = -0.1;` or any negative value，the transparency will take effect again.

![](https://p4.ssl.qhimg.com/t0161ec72d385193802.jpg)

`p1.position.z = -0.1`

**Comment by gordonnl** [comment] 2020-03-02 10:48
Hey, thanks for this issue. It's actually just an issue with the `Program` class in general. Changing the `transparent` property doesn't update the `blendFunc`, outside of the constructor. It's actually a read-only property at that point that I use for creating the render lists. But, I totally agree that it should be editable.

With Polyline, the issue is very clear as you can't pass in transparent to the constructor.

**Comment by akira-cn** [comment] 2020-03-02 10:55
It might not an issue with the `Program` class. I just reuse the geometry from `polyline.mesh.geometry` and re-create a program use `transparent: true`. I found the issue still exists. (See the code I submit above).

**Comment by gordonnl** [comment] 2020-03-02 12:00
ah yes, sorry you're right, that's another issue.

For this, what I'm doing in `Renderer.js` to sort the objects is actually just using their world matrix position, and not the actual geometry bounds: https://github.com/oframe/ogl/blob/master/src/core/Renderer.js#L288

So for your example, for the Polyline, instead of setting the z values to `0.5`, if they were left at `0`, and the mesh's position was `0.5`, it would then sort them correctly.

I wonder if the extra calculations would be worth it, and whether or not that might cause other unexpected issues, in depending on the meshes' geometry.

**Comment by akira-cn** [comment] 2020-03-02 12:47
Thanks.  I resolve the transparency issue by setting the position of the polyline-mesh to the end spot of the path. It works for me.

This is the demo: http://3d.spritejs.org/d3-earth-3.html

I use `sprite-extend-3d.js` and `d3.js` to render a 3D world map. The `sprite-extend-3d.js` (a part of spritejs) is based on OGL.

**Comment by gordonnl** [comment] 2020-03-02 12:52
ah that's so cool! Awesome work.

I think I'll close this issue for now, but it's been really helpful to highlight a couple possible future changes to OGL, cheers!

**Closed by gordonnl** 2020-03-02 12:52 UTC

**Comment by gregja** [comment] 2020-03-02 19:27
Hi @akira-cn ,
you demo of 3D earth is awesome, but there is an issue with Firefox : 
OffscreenCanvas is not defined  (in map.js:10:18)

**Comment by akira-cn** [comment] 2020-03-03 01:29
@gregja Firefox not fully support OffscreenCanvas. I added a polyfill.

```js
if(typeof OffscreenCanvas !== 'function') {
  // firefox polyfill
  window.OffscreenCanvas = function (width, height) {
    const canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    canvas.transferToImageBitmap = function () {
      const ctx = canvas.cloneNode().getContext('2d');
      ctx.translate(0, canvas.height);
      ctx.scale(1, -1);
      ctx.drawImage(canvas, 0, 0);
      return ctx.canvas;
    };
    return canvas;
  };
}
```

**Comment by gregja** [comment] 2020-03-03 06:19
Hi @akira-cn ,
now it works fine on Firefox, you are a magician !! ;)
